/*
 * Swagger Petstore
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.5
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package petstoreApiTests.api;

import org.junit.jupiter.api.Assertions;
import petstoreApiTests.model.ModelApiResponse;
import petstoreApiTests.model.Order;
import petstoreApiTests.ApiClient;
import io.restassured.builder.RequestSpecBuilder;
import io.restassured.filter.log.ErrorLoggingFilter;
import org.junit.Before;
import org.junit.Test;

import java.time.OffsetDateTime;
import java.util.*;

import static io.restassured.config.ObjectMapperConfig.objectMapperConfig;
import static io.restassured.config.RestAssuredConfig.config;
import static petstoreApiTests.GsonObjectMapper.gson;

/**
 * API tests for StoreApi
 */
public class StoreApiTest {

    private StoreApi api;

    @Before
    public void createApi() {
        api = ApiClient.api(ApiClient.Config.apiConfig().reqSpecSupplier(
                () -> new RequestSpecBuilder().setConfig(config().objectMapperConfig(objectMapperConfig().defaultObjectMapper(gson())))
                        .addFilter(new ErrorLoggingFilter())
                        .setBaseUri("https://petstore.swagger.io/v2"))).store();
    }

    /**
     * Invalid ID supplied
     */
/*
    @Test
    public void shouldSee400AfterDeleteOrder() {
        Assertions.assertEquals(400, api.deleteOrder()
                .orderIdPath(new Random().nextDouble()).execute(r -> r.prettyPeek()).as(ModelApiResponse.class).getCode());
    }
*/

    /**
     * Order not found
     */
    @Test
    public void shouldSee404AfterDeleteOrder() {
        Assertions.assertEquals(404, api.deleteOrder()
                .orderIdPath(new Random().nextLong()).execute(r -> r.prettyPeek()).as(ModelApiResponse.class).getCode());
    }
    /**
     * successful operation
     */
    @Test
    public void shouldSee200AfterDeleteOrder() {
        Long orderId = api.placeOrder().body(generateRandomOrderBody()).execute(r -> r.prettyPeek()).as(Order.class).getId();
        ModelApiResponse modelApiResponse = api.deleteOrder().orderIdPath(orderId).execute(r -> r.prettyPeek())
                .as(ModelApiResponse.class);
        Assertions.assertEquals(orderId.toString(), modelApiResponse.getMessage());
        System.out.println(orderId);
        System.out.println(modelApiResponse.getMessage());
        Assertions.assertEquals(200, modelApiResponse.getCode());
    }

    /**
     * successful operation
     */
    @Test
    public void shouldSee200AfterGetInventory() {
        Assertions.assertFalse(api.getInventory().execute(r -> r.prettyPeek()).getBody().jsonPath()
                .getString("available").isEmpty());
    }

    /**
     * successful operation
     */
    @Test
    public void shouldSee200AfterGetOrderById() {
        Order expectedOrder = api.placeOrder().body(generateRandomOrderBody()).execute(r -> r.prettyPeek()).as(Order.class);
        Order actualOrder = api.getOrderById().orderIdPath(expectedOrder.getId()).execute(r -> r.prettyPeek()).as(Order.class);
        System.out.println(expectedOrder);
        System.out.println(actualOrder);
        Assertions.assertEquals(expectedOrder, actualOrder);
    }

    /**
     * Invalid ID supplied
     */
    /*
    @Test
    public void shouldSee400AfterGetOrderById() {
        Assertions.assertEquals(400, api.getOrderById()
                .orderIdPath(new Random().nextDouble()).execute(r -> r.prettyPeek()).as(ModelApiResponse.class).getCode());
    }
*/

    /**
     * Order not found
     */
    @Test
    public void shouldSee404AfterGetOrderById() {
        Assertions.assertEquals(1, api.getOrderById()
                .orderIdPath(new Random().nextLong()).execute(r -> r.prettyPeek()).as(ModelApiResponse.class).getCode());
    }

    /**
     * successful operation
     */
    @Test
    public void shouldSee200AfterPlaceOrder() {
        Order expectedOrder = generateRandomOrderBody();
        Order actualOrder = api.placeOrder().body(expectedOrder).execute(r -> r.prettyPeek()).as(Order.class);
        expectedOrder.setId(actualOrder.getId());
        System.out.println(expectedOrder);
        System.out.println(actualOrder);
        Assertions.assertEquals(expectedOrder, actualOrder);
//        Assertions.assertEquals(200, api.placeOrder().body(actualOrder)
//                .execute(r -> r.prettyPeek()).as(ModelApiResponse.class).getCode());

    }

    /**
     * Invalid Order
     */
    /*
    @Test
    public void shouldSee400AfterPlaceOrder() {
        Order body = api.placeOrder()
                .body(generateRandomOrderBody()).execute(r -> r.prettyPeek()).as(Order.class);
        System.out.println(body);
        Assertions.assertEquals(400, api.placeOrder()
                .body(body).execute(r -> r.prettyPeek()).as(ModelApiResponse.class).getCode());
    }
     */

    private Order generateRandomOrderBody() {
        return new Order()
                .id(new Random().nextLong())
                .petId(new Random().nextLong())
                .status(Order.StatusEnum.APPROVED)
                .complete(true)
                .quantity(0)
                .shipDate(OffsetDateTime.parse("2021-07-22T18:21:10.129Z"));    }
}
